# Generated by Django 3.2.8 on 2021-11-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(default=None, upload_to=None),
        ),
    ]
